### ISSUE TITLE
Cannot change sound output to arc

### ISSUE THREAD

**Issue by 1rV1N-git** [madmicio/LG-WebOS-Remote-Control#108]
Model: 49UJ740V-ZA
```
Jan 15 00:25:24 rockpi-4b homeassistant[998]: 2023-01-15 00:25:24.741 ERROR (MainThread) [homeassistant.util.logging] Exception in async_signal_handler when dispatching 'webostv': ({'entity_id': ['media_player.lg'], 'sound_output': 'external_arc', 'method': 'async_select_sound_output'},)
Jan 15 00:25:24 rockpi-4b homeassistant[998]: Traceback (most recent call last):
Jan 15 00:25:24 rockpi-4b homeassistant[998]:   File "/usr/local/lib/python3.10/site-packages/aiowebostv/webos_client.py", line 939, in change_sound_output
Jan 15 00:25:24 rockpi-4b homeassistant[998]:     return await self.request(ep.CHANGE_SOUND_OUTPUT, {"output": output})
Jan 15 00:25:24 rockpi-4b homeassistant[998]:   File "/usr/local/lib/python3.10/site-packages/aiowebostv/webos_client.py", line 616, in request
Jan 15 00:25:24 rockpi-4b homeassistant[998]:     raise WebOsTvResponseTypeError(response)
Jan 15 00:25:24 rockpi-4b homeassistant[998]: aiowebostv.exceptions.WebOsTvResponseTypeError: {'type': 'error', 'id': 39, 'error': '500 Application error', 'payload': {'returnValue': False, 'errorText': 'There is No matched extended item: soundOutput'}}
Jan 15 00:25:24 rockpi-4b homeassistant[998]:
Jan 15 00:25:24 rockpi-4b homeassistant[998]: The above exception was the direct cause of the following exception:
Jan 15 00:25:24 rockpi-4b homeassistant[998]:
Jan 15 00:25:24 rockpi-4b homeassistant[998]: Traceback (most recent call last):
Jan 15 00:25:24 rockpi-4b homeassistant[998]:   File "/usr/src/homeassistant/homeassistant/components/webostv/media_player.py", line 191, in async_signal_handler
Jan 15 00:25:24 rockpi-4b homeassistant[998]:     await getattr(self, data["method"])(**params)
Jan 15 00:25:24 rockpi-4b homeassistant[998]:   File "/usr/src/homeassistant/homeassistant/components/webostv/media_player.py", line 102, in cmd_wrapper
Jan 15 00:25:24 rockpi-4b homeassistant[998]:     raise HomeAssistantError(
Jan 15 00:25:24 rockpi-4b homeassistant[998]: homeassistant.exceptions.HomeAssistantError: Error calling async_select_sound_output on entity media_player.lg, state:on
Jan 15 00:25:24 rockpi-4b homeassistant[998]:

```

**Comment by 1rV1N-git** [comment]
correct value external_speaker
