### ISSUE TITLE
Cannot change sound output to ARC or optical

### ISSUE THREAD

**Issue by lonepinetech** [madmicio/LG-WebOS-Remote-Control#140]
LG TV WebOS Model 49UUJ6300

I can change the sound output on the remote to internal speaker or internal speaker+optical just fine. But trying to choose HDMI or optical will not work. No sound source is highlighted and an error thrown in the log.

I have two LG tvs and the sound output (HDMI) works fine on the newer one?

**Comment by lonepinetech** [comment]
Logger: homeassistant.util.logging
Source: util/logging.py:101
First occurred: 9:50:47 AM (1 occurrences)
Last logged: 9:50:47 AM

Exception in async_signal_handler when dispatching 'webostv': ({'entity_id': ['media_player.lg_webos_tv'], 'sound_output': 'external_optical', 'method': 'async_select_sound_output'},) Traceback (most recent call last): File "/usr/local/lib/python3.11/site-packages/aiowebostv/webos_client.py", line 949, in change_sound_output return await self.request(ep.CHANGE_SOUND_OUTPUT, {"output": output}) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/aiowebostv/webos_client.py", line 626, in request raise WebOsTvResponseTypeError(response) aiowebostv.exceptions.WebOsTvResponseTypeError: {'type': 'error', 'id': 915, 'error': '500 Application error', 'payload': {'returnValue': False, 'errorText': 'There is No matched extended item: soundOutput'}} The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/webostv/media_player.py", line 183, in async_signal_handler await getattr(self, data["method"])(**params) File "/usr/src/homeassistant/homeassistant/components/webostv/media_player.py", line 98, in cmd_wrapper raise HomeAssistantError( homeassistant.exceptions.HomeAssistantError: Error calling async_select_sound_output on entity media_player.lg_webos_tv, state:on

**Comment by lonepinetech** [comment]
Probably an LG integration issue

**Comment by stievenkowalski** [comment]
> LG TV WebOS Model 49UUJ6300
> 
> I can change the sound output on the remote to internal speaker or internal speaker+optical just fine. But trying to choose HDMI or optical will not work. No sound source is highlighted and an error thrown in the log.
> 
> I have two LG tvs and the sound output (HDMI) works fine on the newer one?

I have the exact same issue. LG TV WebOS Model OLED65E6D

**Comment by stievenkowalski** [comment]
2024-01-09 13:01:28.186 ERROR (MainThread) [homeassistant.util.logging] Exception in async_signal_handler when dispatching 'webostv': ({'entity_id': ['media_player.lg_oled65e6d_salon'], 'sound_output': 'external_optical', 'method': 'async_select_sound_output'},)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiowebostv/webos_client.py", line 949, in change_sound_output
    return await self.request(ep.CHANGE_SOUND_OUTPUT, {"output": output})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiowebostv/webos_client.py", line 626, in request
    raise WebOsTvResponseTypeError(response)
aiowebostv.exceptions.WebOsTvResponseTypeError: {'type': 'error', 'id': 45, 'error': '500 Application error', 'payload': {'returnValue': False, 'errorText': 'There is No matched extended item: soundOutput'}}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/webostv/media_player.py", line 183, in async_signal_handler
    await getattr(self, data["method"])(**params)
  File "/usr/src/homeassistant/homeassistant/components/webostv/media_player.py", line 98, in cmd_wrapper
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Error calling async_select_sound_output on entity media_player.lg_oled65e6d_salon, state:on
