### ISSUE TITLE
Poweron button does not work

### ISSUE THREAD

**Issue by pippo73** [madmicio/LG-WebOS-Remote-Control#6]
Pushing the power on button does not turn on the tv.
Instead I get the following errors:

- on the interface
`Failed to call service media_player/toggle. extra keys not allowed @ data['message']
`

- in developer -> logs
```
Log Details (ERROR)
Logger: homeassistant.helpers.script
Source: helpers/script.py:802
First occurred: 10:08:00 AM (1 occurrences)
Last logged: 10:08:00 AM

Error executing script. Invalid data for call_service at pos 1: extra keys not allowed @ data['message']
```
and
```

Log Details (ERROR)
Logger: homeassistant.components.websocket_api.http.connection.2870756496
Source: core.py:1210
Integration: websocket_api (documentation, issues)
First occurred: 10:08:00 AM (1 occurrences)
Last logged: 10:08:00 AM

extra keys not allowed @ data['message']
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 134, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1232, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1255, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    self._platforms.values(), func, call, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 412, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 600, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 443, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 708, in async_toggle
    await self.async_turn_on()
  File "/usr/src/homeassistant/homeassistant/components/webostv/media_player.py", line 308, in async_turn_on
    await self._on_script.async_run()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 802, in async_run
    await run.async_run()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 523, in async_run
    await self._async_run()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 540, in _async_run
    await self._async_step(log_exceptions=not propagate_exceptions)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 154, in _async_step
    self, f"_async_{cv.determine_script_action(self._action)}_step"
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 624, in _async_call_service_step
    *self._prep_call_service_step(), blocking=True, context=self._context
  File "/usr/src/homeassistant/homeassistant/core.py", line 1210, in async_call
    processed_data = handler.schema(service_data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: extra keys not allowed @ data['message']
```

Running on a Raspbian  + "HOME ASSISTANT SUPERVISED"

**Comment by PiotrMachowski** [comment]
Could you check if this error still exist in the latest version?

**Comment by pippo73** [comment]
Hi Piotr, 
I'm sorry but it seems giving the same problem:
```
Log Details (ERROR)
Logger: homeassistant.components.websocket_api.http.connection.2881897424
Source: core.py:1210
Integration: websocket_api (documentation, issues)
First occurred: 10:19:00 PM (1 occurrences)
Last logged: 10:19:00 PM

extra keys not allowed @ data['message']
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 134, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1232, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1255, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    self._platforms.values(), func, call, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 412, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 600, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 443, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 708, in async_toggle
    await self.async_turn_on()
  File "/usr/src/homeassistant/homeassistant/components/webostv/media_player.py", line 308, in async_turn_on
    await self._on_script.async_run()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 802, in async_run
    await run.async_run()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 523, in async_run
    await self._async_run()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 540, in _async_run
    await self._async_step(log_exceptions=not propagate_exceptions)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 154, in _async_step
    self, f"_async_{cv.determine_script_action(self._action)}_step"
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 624, in _async_call_service_step
    *self._prep_call_service_step(), blocking=True, context=self._context
  File "/usr/src/homeassistant/homeassistant/core.py", line 1210, in async_call
    processed_data = handler.schema(service_data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: extra keys not allowed @ data['message']
```
```

Log Details (ERROR)
Logger: homeassistant.helpers.script
Source: helpers/script.py:802
First occurred: 10:19:00 PM (1 occurrences)
Last logged: 10:19:00 PM

Error executing script. Invalid data for call_service at pos 1: extra keys not allowed @ data['message']
Connection lost. Reconnecting…

```

**Comment by PiotrMachowski** [comment]
That's really weird, there is no `message` word in entire cards code. Are you sure that it is not an issue with your media player?

**Comment by pippo73** [comment]
> That's really weird, there is no `message` word in entire cards code. Are you sure that it is not an issue with your media player?

The fact is that if I turn on the TV and I use the plugin, the other buttons work!
and if I send a magic packet from the linux command shell 
`$ wakeonlan 20:17:42:34:8b:48` the tv turns on!

**Comment by PiotrMachowski** [comment]
Can you turn on your TV by calling a service from dev tools?

**Comment by pippo73** [comment]
How strange...
if I turn off the tv... it works.

if I try to turn it on. it gives me the same error... any idea what it could be?

**Comment by PiotrMachowski** [comment]
It's not an issue with this card, so I'm going to close this issue.

It seems that your `webostv` platform config is invalid, you can show your config below if you have problem with fixing it.
